### ISSUE TITLE
2.9.4 can not show unsigned transaction qrcode

### ISSUE THREAD

**Issue by tim-le** [fyookball/electrum#250]
message box : 

type object 'QApplication' has no attribute 'primaryScreen'

**Comment by tim-le** [comment]
btw, is this issue fixed in 2.9.4？
https://github.com/fyookball/electrum/issues/166

**Comment by tim-le** [comment]
both win and macos have such problem

**Comment by fyookball** [comment]
@tim-le steps to create this bug? 

Is this the same as #166?  #166 is not fixed yet.  It is non trivial as it involves changing how the QR is done

**Comment by tim-le** [comment]
in steps of #166 , the previous version could show the unsigned raw transaction as qrcode,  2.9.4 cannot.

**Comment by molecular** [comment]
@tim-le: #166 is not done, can we disucss the "can't display qr-code issue there"? It's working for me in 2.9.4

**Comment by fyookball** [comment]
@molecular most likely.

**Comment by fyookball** [comment]
fixed

https://github.com/fyookball/electrum/commit/4237b18db5b85ede502f3775171b0dbcb520429c
