### ISSUE TITLE
Cannot synchronize : assertion failed

### ISSUE THREAD

**Issue by uski** [fyookball/electrum#524]
I am trying to synchronize an address which was used for Bitcoin mining.
The synchronization fails after a few transaction with this on electron-cash 3.1.2 : 

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/x/Downloads/Electron Cash-3.1.2/lib/network.py", line 959, in run
    self.wait_on_sockets()
  File "/home/x/Downloads/Electron Cash-3.1.2/lib/network.py", line 926, in wait_on_sockets
    self.process_responses(interface)
  File "/home/x/Downloads/Electron Cash-3.1.2/lib/network.py", line 614, in process_responses
    self.process_response(interface, response, callbacks)
  File "/home/x/Downloads/Electron Cash-3.1.2/lib/network.py", line 563, in process_response
    callback(response)
  File "/home/x/Downloads/Electron Cash-3.1.2/lib/synchronizer.py", line 153, in tx_response
    self.wallet.receive_tx_callback(tx_hash, tx, tx_height)
  File "/home/x/Downloads/Electron Cash-3.1.2/lib/wallet.py", line 756, in receive_tx_callback
    self.add_transaction(tx_hash, tx)
  File "/home/x/Downloads/Electron Cash-3.1.2/lib/wallet.py", line 691, in add_transaction
    assert isinstance(addr, Address)
AssertionError

If I add print(txi) right before the assert, it gives something like this : 

{'prevout_hash': '0000000000000000000000000000000000000000000000000000000000000000', 'prevout_n': some_integer, 'sequence': same_as_prevout_n, 'type': 'coinbase', 'scriptSig': 'lots of hex digits'}

Any clue ? Definitely looks like a bug as it's an assertion failure

**Comment by kyuupichan** [comment]
This was fixed in git a while ago; please wait for the next release or run from git.

**Comment by uski** [comment]
I just downloaded a ZIP file from GitHub and the issue is still there.

**Comment by uski** [comment]
Actually it's a different stacktrace, see below.
I started from scratch with a new wallet file.

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/x/Downloads/electron_cash_git/electrum-master/lib/network.py", line 959, in run
    self.wait_on_sockets()
  File "/home/x/Downloads/electron_cash_git/electrum-master/lib/network.py", line 926, in wait_on_sockets
    self.process_responses(interface)
  File "/home/x/Downloads/electron_cash_git/electrum-master/lib/network.py", line 614, in process_responses
    self.process_response(interface, response, callbacks)
  File "/home/x/Downloads/electron_cash_git/electrum-master/lib/network.py", line 563, in process_response
    callback(response)
  File "/home/x/Downloads/electron_cash_git/electrum-master/lib/synchronizer.py", line 153, in tx_response
    self.wallet.receive_tx_callback(tx_hash, tx, tx_height)
  File "/home/x/Downloads/electron_cash_git/electrum-master/lib/wallet.py", line 754, in receive_tx_callback
    self.add_transaction(tx_hash, tx)
  File "/home/x/Downloads/electron_cash_git/electrum-master/lib/wallet.py", line 695, in add_transaction
    if self.is_mine(addr):
  File "/home/x/Downloads/electron_cash_git/electrum-master/lib/wallet.py", line 369, in is_mine
    assert isinstance(address, (Address, PublicKey, ScriptOutput))

**Comment by kyuupichan** [comment]
Should be fixed now.
